### ISSUE TITLE
Feature: Convert boilerplate into theme

### ISSUE THREAD

**Issue by daviddarnes** [daviddarnes/alembic#11]
## TODO:

- [x] Create `gemspec` file
- [x] Test theme out
- [ ] Allow easy way to create new config file
- [ ] Write up installation and usage in `README`
- [x] Submit RubyGems.org
- [ ] Test if users of theme can customise files

**Comment by daviddarnes** [comment]
Interesting tool for downloading specific subdirectories, could be ideal for downloading the demo content for the theme https://minhaskamal.github.io/DownGit/#/home

**Comment by daviddarnes** [comment]
Link to download demo content https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/daviddarnes/alembic/tree/theme-gem/demo

**Comment by daviddarnes** [comment]
Need to setup logo options. SVG and png options
